### ISSUE TITLE
Tanslation to English

### ISSUE THREAD

**Issue by killo3967** [yiding-he/hydrogen-wkhtmltopdf#1]
I think it's a good gui, please translate it to english.

Thanks

**Comment by yiding-he** [comment]
Why not, thanks for loving this project. I think it would be nice if I extract the text resources and make it easy for others to add other languages. This will be done in a week.

**Comment by yiding-he** [comment]
Released [here](https://github.com/yiding-he/hydrogen-wkhtmltopdf/releases/tag/2024-10-28). 
Please feel free to create new issues if you encounter further problems.
